#!/bin/bash

# Setup script for Supabase system_config table

echo "=== CreditLine Supabase Setup ==="
echo ""
echo "To execute the SQL script that creates the system_config table:"
echo "1. Go to Supabase Console: https://app.supabase.com"
echo "2. Select your CreditLine project"
echo "3. Go to SQL Editor"
echo "4. Click 'New Query'"
echo "5. Copy the contents of 'create_system_config.sql' and paste it"
echo "6. Click 'Run'"
echo ""
echo "The script will:"
echo "  - Create system_config table with tasa_interes and impuesto_retraso"
echo "  - Enable Row-Level Security (RLS)"
echo "  - Create RLS policies for admin access only"
echo "  - Insert default configuration values (10.0% and 5.0%)"
echo ""
echo "After running the SQL script, you can test the backend endpoints:"
echo ""
echo "1. List users:"
echo "   curl -X GET http://localhost:8000/api/users/list/ \\"
echo "     -H 'Authorization: Bearer YOUR_TOKEN'"
echo ""
echo "2. Create user:"
echo "   curl -X POST http://localhost:8000/api/users/create/ \\"
echo "     -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"nombre\": \"Juan\", \"email\": \"juan@example.com\", \"rol\": \"OPERARIO\", \"password\": \"securepass123\"}'"
echo ""
echo "3. Get system config:"
echo "   curl -X GET http://localhost:8000/api/users/system-config/ \\"
echo "     -H 'Authorization: Bearer YOUR_TOKEN'"
echo ""
echo "4. Update system config:"
echo "   curl -X PUT http://localhost:8000/api/users/system-config/update/ \\"
echo "     -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"tasa_interes\": 12.5, \"impuesto_retraso\": 6.0}'"
